//! Synthetic, redistributable layout tests; the supplied corpus stays local.
use std::path::Path;
#[cfg(feature = "fmt-matlab")]
use std::path::PathBuf;

use nirs4all_formats::{builtin_probes, open_bytes, open_path, AxisKind, SignalType};

fn word(bytes: &mut [u8], offset: usize, value: u32) {
    bytes[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
}

fn text(value: &str, width: usize) -> Vec<u8> {
    let mut out: Vec<_> = value.encode_utf16().flat_map(u16::to_le_bytes).collect();
    out.resize(width, 0);
    out
}

fn block(out: &mut Vec<u8>, kind: u32, id: u32, stride: u32, data: &[u8]) {
    for value in [kind, id, data.len() as u32 / stride, stride] {
        out.extend(value.to_le_bytes());
    }
    out.extend(data);
}

fn group(name: &str, range: &str) -> Vec<u8> {
    let mut out = text(name, 600);
    word(&mut out, 80, 1);
    out[88..88 + range.len()].copy_from_slice(range.as_bytes());
    out
}

fn synthetic() -> Vec<u8> {
    let mut out = vec![0; 768];
    let magic = b"Non-design data File Generated by The Unscrambler 35 (Unknown)\x1a";
    out[..magic.len()].copy_from_slice(magic);
    word(&mut out, 92, 35);
    word(&mut out, 248, 1);
    word(&mut out, 252, 768);
    let mut header = vec![0; 276];
    header[4..84].copy_from_slice(&text("RawData", 80));
    word(&mut header, 172, 5);
    word(&mut header, 176, 2);
    block(&mut out, 11, 1000, 276, &header);
    block(&mut out, 30, 1001, 112, &[0; 112]);
    block(&mut out, 13, 1002, 128, &[0; 256]);
    block(&mut out, 14, 1003, 92, &[0; 460]);
    block(&mut out, 26, 1004, 600, &group("All Samples", "1-2"));
    let groups = [
        group("All Variables", "1-5"),
        group("combined", "2-5"),
        group("nir", "2-3"),
        group("nmr", "4-5"),
    ]
    .concat();
    block(&mut out, 26, 1005, 600, &groups);
    block(
        &mut out,
        12,
        1006,
        32,
        &["protein", "*", "*", "*", "*"]
            .map(|s| text(s, 32))
            .concat(),
    );
    // Deliberately duplicate sample identifiers: row order is authoritative.
    block(
        &mut out,
        12,
        1007,
        32,
        &[text("same", 32), text("same", 32)].concat(),
    );
    block(&mut out, 12, 1008, 32, &text("RawData", 32));
    let data: Vec<_> = [
        7.0_f32, -9.973e23, 10.0, 20.0, 11.0, 21.0, 30.0, 40.0, 31.0, 41.0,
    ]
    .into_iter()
    .flat_map(f32::to_le_bytes)
    .collect();
    block(&mut out, 1, 1009, 4, &data);
    out
}

#[test]
fn native_groups_targets_missing_values_and_memory_reads() {
    let bytes = synthetic();
    let probes = builtin_probes(&bytes, Path::new("renamed.bin"));
    assert_eq!(probes[0].format, "unscrambler-00d");
    let records = open_bytes("renamed.bin", &bytes).unwrap();
    assert_eq!(records.len(), 2);
    assert_eq!(records[0].signals.len(), 2);
    assert_eq!(records[0].signals["nir"].values, [10.0, 11.0]);
    assert_eq!(records[1].signals["nmr"].values, [40.0, 41.0]);
    assert_eq!(records[0].signals["nir"].axis.kind, AxisKind::Index);
    assert_eq!(records[0].signal_type, SignalType::Unknown);
    assert_eq!(records[0].targets["protein"], 7.0);
    assert!(records[1].targets["protein"].is_null());
    assert_eq!(records[1].quality_flags, ["missing_values"]);
    assert_eq!(records[1].metadata["sample_index"], 1);
    assert_eq!(
        records[0].metadata["vendor_dataset"]["column_descriptors"]
            .as_array()
            .unwrap()
            .len(),
        5
    );
    assert!(!records[1].metadata.contains_key("vendor_dataset"));
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("dataset.00D");
    std::fs::write(&path, &bytes).unwrap();
    let from_path = open_path(&path).unwrap();
    assert_eq!(from_path[1].targets, records[1].targets);
    assert_eq!(from_path[0].signals, records[0].signals);
}

#[test]
fn native_rejects_truncation_invalid_counts_revisions_and_selections() {
    let bytes = synthetic();
    for len in [64, 767, 783, 1000, bytes.len() - 1] {
        assert!(open_bytes("bad.00d", &bytes[..len]).is_err());
    }
    let mut bad = bytes.clone();
    bad[48..50].copy_from_slice(b"99");
    assert!(open_bytes("bad.00d", &bad).is_err());
    let mut bad = bytes.clone();
    word(&mut bad, 768 + 8, u32::MAX);
    assert!(open_bytes("bad.00d", &bad).is_err());
    let mut bad = bytes.clone();
    word(&mut bad, 768 + 16 + 172, 6);
    assert!(open_bytes("bad.00d", &bad).is_err());
    let pos = bytes.windows(3).position(|s| s == b"2-3").unwrap();
    for range in [b"0-3", b"2-9", b"3-2"] {
        let mut bad = bytes.clone();
        bad[pos..pos + 3].copy_from_slice(range);
        assert!(open_bytes("bad.00d", &bad).is_err());
    }
    let mut bad = bytes.clone();
    bad.extend([0; 16]);
    assert!(open_bytes("bad.00d", &bad).is_err());
    assert!(builtin_probes(b"not an Unscrambler file", Path::new("extension_only.00D")).is_empty());
}

#[test]
fn native_follows_header_offset_and_rejects_corrupt_metadata() {
    let bytes = synthetic();
    let mut relocated = bytes[..768].to_vec();
    relocated.extend([0; 16]);
    relocated.extend(&bytes[768..]);
    word(&mut relocated, 252, 784);
    assert_eq!(
        open_bytes("relocated.00D", &relocated).unwrap()[0].signals["nir"].values,
        [10.0, 11.0]
    );
    for (offset, value) in [(92, 34), (248, 2), (252, 0), (252, u32::MAX), (780, 0)] {
        let mut bad = bytes.clone();
        word(&mut bad, offset, value);
        assert!(open_bytes("bad.00D", &bad).is_err());
    }
    let pos = bytes.windows(3).position(|s| s == b"4-5").unwrap();
    let mut overlap = bytes.clone();
    overlap[pos..pos + 3].copy_from_slice(b"3-4");
    assert!(open_bytes("overlap.00d", &overlap).is_err());
    let pos = bytes.windows(3).position(|s| s == b"1-2").unwrap();
    let mut repeated = bytes.clone();
    repeated[pos..pos + 5].copy_from_slice(b"1,1,2");
    assert!(open_bytes("repeated.00d", &repeated).is_err());
    let label = bytes
        .windows(14)
        .position(|s| s == text("protein", 14))
        .unwrap();
    let mut invalid_utf16 = bytes.clone();
    invalid_utf16[label..label + 2].copy_from_slice(&0xd800_u16.to_le_bytes());
    assert!(open_bytes("invalid.00d", &invalid_utf16).is_err());
    let mut unicode = bytes.clone();
    unicode[label..label + 32].copy_from_slice(&text("protéine🧪", 32));
    assert_eq!(
        open_bytes("unicode.00d", &unicode).unwrap()[0].targets["protéine🧪"],
        7.0
    );
}

#[cfg(feature = "fmt-matlab")]
mod mat_export {
    use super::*;

    fn element(out: &mut Vec<u8>, kind: u32, data: &[u8], big: bool) {
        let encode = |v: u32| {
            if big {
                v.to_be_bytes()
            } else {
                v.to_le_bytes()
            }
        };
        out.extend(encode(kind));
        out.extend(encode(data.len() as u32));
        out.extend(data);
        out.resize(out.len().next_multiple_of(8), 0);
    }

    fn matrix(
        name: &str,
        class: u32,
        rows: u32,
        cols: u32,
        kind: u32,
        data: &[u8],
        big: bool,
    ) -> Vec<u8> {
        let encode = |v: u32| {
            if big {
                v.to_be_bytes()
            } else {
                v.to_le_bytes()
            }
        };
        let mut payload = Vec::new();
        element(&mut payload, 6, &[encode(class), encode(0)].concat(), big);
        element(&mut payload, 5, &[encode(rows), encode(cols)].concat(), big);
        element(&mut payload, 1, name.as_bytes(), big);
        element(&mut payload, kind, data, big);
        let mut out = Vec::new();
        element(&mut out, 14, &payload, big);
        out
    }

    fn char_matrix(name: &str, labels: &[&str], big: bool) -> Vec<u8> {
        let labels: Vec<Vec<u16>> = labels.iter().map(|s| s.encode_utf16().collect()).collect();
        let width = labels.iter().map(Vec::len).max().unwrap();
        let mut data = Vec::new();
        for col in 0..width {
            for label in &labels {
                let ch = label.get(col).copied().unwrap_or(u16::from(b' '));
                data.extend(if big {
                    ch.to_be_bytes()
                } else {
                    ch.to_le_bytes()
                });
            }
        }
        matrix(name, 4, labels.len() as u32, width as u32, 4, &data, big)
    }

    fn export(big: bool, compressed: bool, ambiguous: bool) -> Vec<u8> {
        let mut out = vec![0; 128];
        out[..20].copy_from_slice(b"MATLAB 5.0 MAT-file ");
        out[124..126].copy_from_slice(if big { &[1, 0] } else { &[0, 1] });
        out[126..].copy_from_slice(if big { b"MI" } else { b"IM" });
        let data: Vec<_> = [
            7.0_f64,
            f64::NAN,
            10.0,
            20.0,
            11.0,
            21.0,
            30.0,
            40.0,
            31.0,
            41.0,
        ]
        .into_iter()
        .flat_map(|v| {
            if big {
                v.to_be_bytes()
            } else {
                v.to_le_bytes()
            }
        })
        .collect();
        let mut payload = char_matrix("VarLabels0", &["protein", "*", "*", "*", "*"], big);
        payload.extend(char_matrix("ObjLabels", &["same", "same"], big));
        payload.extend(matrix("any_matrix_name", 6, 2, 5, 9, &data, big));
        if ambiguous {
            payload.extend(matrix("other_matrix", 6, 2, 5, 9, &data, big));
        }
        if compressed {
            use std::io::Write;
            let mut encoder =
                flate2::write::ZlibEncoder::new(Vec::new(), flate2::Compression::default());
            encoder.write_all(&payload).unwrap();
            element(&mut out, 15, &encoder.finish().unwrap(), big);
        } else {
            out.extend(payload);
        }
        out
    }

    #[test]
    fn labelled_mat_exports_preserve_columns_without_inventing_calibration() {
        for big in [false, true] {
            for compressed in [false, true] {
                let records = open_bytes("arbitrary.MAT", &export(big, compressed, false)).unwrap();
                assert_eq!(records.len(), 2);
                assert_eq!(records[0].provenance.format, "matlab-unscrambler-export");
                assert_eq!(
                    records[0].signals["signal_2"].values,
                    [10.0, 11.0, 30.0, 31.0]
                );
                assert_eq!(
                    records[1].signals["signal_2"].values,
                    [20.0, 21.0, 40.0, 41.0]
                );
                assert_eq!(
                    records[0].metadata["variable_labels"]
                        .as_array()
                        .unwrap()
                        .len(),
                    5
                );
                assert!(records[1].targets["protein"].is_null());
            }
        }
        assert!(open_bytes("ambiguous.mat", &export(false, false, true)).is_err());
    }

    #[test]
    fn mat_export_unicode_empty_labels_and_malformed_numeric_arrays() {
        for big in [false, true] {
            let mut bytes = export(big, false, false)[..128].to_vec();
            bytes.extend(char_matrix(
                "VarLabels0",
                &["protéine🧪", "*", "*", "*", ""],
                big,
            ));
            bytes.extend(char_matrix("ObjLabels", &["échantillon🧪", ""], big));
            let data: Vec<_> = (0..10)
                .flat_map(|i| {
                    let v = f64::from(i);
                    if big {
                        v.to_be_bytes()
                    } else {
                        v.to_le_bytes()
                    }
                })
                .collect();
            bytes.extend(matrix("data", 6, 2, 5, 9, &data, big));
            let records = open_bytes("unicode.mat", &bytes).unwrap();
            assert_eq!(records[0].targets["protéine🧪"], 0.0);
            assert_eq!(records[0].metadata["sample_id"], "échantillon🧪");
            assert_eq!(records[1].metadata["sample_id"], "");
            assert_eq!(records[0].signals["signal_2"].values.len(), 4);
        }
        let mut bytes = export(false, false, false);
        let marker = [
            6_u32.to_le_bytes(),
            8_u32.to_le_bytes(),
            6_u32.to_le_bytes(),
        ]
        .concat();
        let flag = bytes
            .windows(marker.len())
            .position(|b| b == marker)
            .unwrap()
            + 8;
        bytes[flag..flag + 4].copy_from_slice(&(6_u32 | 0x800).to_le_bytes());
        assert!(open_bytes("complex.mat", &bytes).is_err());
        let bytes = export(false, false, false);
        for len in [128, 200, bytes.len() - 1] {
            assert!(open_bytes("truncated.mat", &bytes[..len]).is_err());
        }
    }
}

#[cfg(feature = "fmt-matlab")]
fn workspace_file(path: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(path)
}

#[cfg(feature = "fmt-matlab")]
#[test]
fn local_paired_corpus_matches_every_value_when_present() {
    let find = |final_path: &str, incoming: &str| {
        let path = workspace_file(final_path);
        if path.exists() {
            path
        } else {
            workspace_file(incoming)
        }
    };
    let native = find(
        "samples_local/unscrambler/SENUCSPE.00D",
        "samples_todo/SENUCSPE.00D",
    );
    let matlab = find(
        "samples_local/matlab/SENUCSPE.mat",
        "samples_todo/SENUCSPE.mat",
    );
    if !native.exists() || !matlab.exists() {
        return;
    }
    let native_records = open_path(&native).unwrap();
    let mat_records = open_path(&matlab).unwrap();
    assert_eq!(native_records.len(), 26);
    assert_eq!(mat_records.len(), 26);
    for (native, mat) in native_records.iter().zip(&mat_records) {
        assert_eq!(native.signals.len(), 6);
        assert_eq!(native.targets.len(), 66);
        assert_eq!(native.signals["nirkogt"].values.len(), 1050);
        assert_eq!(native.signals["cpmgmkogt"].values.len(), 4096);
        assert_eq!(native.signals["FIDkogt"].values.len(), 5000);
        assert_eq!(native.metadata["sample_id"], mat.metadata["sample_id"]);
        assert_eq!(
            native.metadata["missing_value_count"],
            mat.metadata["missing_value_count"]
        );
        for (key, value) in &native.targets {
            if value.is_null() {
                assert!(mat.targets[key].is_null());
            } else {
                close(value.as_f64().unwrap(), mat.targets[key].as_f64().unwrap());
            }
        }
        for (name, signal) in &native.signals {
            let columns = native.metadata["signal_columns"][name].as_array().unwrap();
            for (value, col) in signal.values.iter().zip(columns) {
                let offset = col.as_u64().unwrap() as usize - 66;
                close(*value, mat.signals["signal_67"].values[offset]);
            }
        }
    }
}

#[cfg(feature = "fmt-matlab")]
fn close(a: f64, b: f64) {
    assert!(
        (a.is_nan() && b.is_nan()) || (a - b).abs() <= 1e-6 * b.abs().max(1.0),
        "{a} != {b}"
    );
}
