#!/usr/bin/env python3
"""Generate public Unscrambler/MAT fixtures from invented values (stdlib only)."""

import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LABELS = ["protein", "*", "*", "*", "*"]
OBJECTS = ["sample_a", "sample_b"]
VALUES = [7.0, float("nan"), 10.0, 20.0, 11.0, 21.0, 30.0, 40.0, 31.0, 41.0]


def fixed_text(value: str, size: int) -> bytes:
    return value.encode("utf-16le").ljust(size, b"\0")


def native() -> bytes:
    out = bytearray(768)
    magic = b"Non-design data File Generated by The Unscrambler 35 (Unknown)\x1a"
    out[: len(magic)] = magic
    for offset, value in [(80, 1000), (84, 9), (88, 30), (92, 35), (248, 1), (252, 768)]:
        struct.pack_into("<I", out, offset, value)

    def block(kind: int, identifier: int, stride: int, data: bytes) -> None:
        out.extend(struct.pack("<4I", kind, identifier, len(data) // stride, stride))
        out.extend(data)

    def group(name: str, selection: str) -> bytes:
        data = bytearray(600)
        data[:80] = fixed_text(name, 80)
        struct.pack_into("<2I", data, 80, 1, 0)
        data[88 : 88 + len(selection)] = selection.encode("ascii")
        return bytes(data)

    header = bytearray(276)
    header[4:84] = fixed_text("Synthetic", 80)
    struct.pack_into("<2I", header, 172, len(LABELS), len(OBJECTS))
    block(11, 1000, 276, header)
    block(30, 1001, 112, bytes(112))
    block(13, 1002, 128, bytes(128 * len(OBJECTS)))
    block(14, 1003, 92, bytes(92 * len(LABELS)))
    block(26, 1004, 600, group("All Samples", "1-2"))
    block(
        26,
        1005,
        600,
        b"".join(
            [
                group("All Variables", "1-5"),
                group("combined", "2-5"),
                group("nir", "2-3"),
                group("nmr", "4-5"),
            ]
        ),
    )
    block(12, 1006, 32, b"".join(fixed_text(s, 32) for s in LABELS))
    block(12, 1007, 32, b"".join(fixed_text(s, 32) for s in OBJECTS))
    block(12, 1008, 32, fixed_text("Synthetic", 32))
    values = [-9.973e23 if value != value else value for value in VALUES]
    block(1, 1009, 4, struct.pack(f"<{len(values)}f", *values))
    return bytes(out)


def mat() -> bytes:
    def element(kind: int, data: bytes) -> bytes:
        return struct.pack("<2I", kind, len(data)) + data + bytes(-len(data) % 8)

    def matrix(name: str, array_class: int, rows: int, cols: int, kind: int, data: bytes) -> bytes:
        return element(
            14,
            b"".join(
                [
                    element(6, struct.pack("<2I", array_class, 0)),
                    element(5, struct.pack("<2i", rows, cols)),
                    element(1, name.encode("ascii")),
                    element(kind, data),
                ]
            ),
        )

    def labels(name: str, values: list[str]) -> bytes:
        width = max(map(len, values))
        chars = [ord(value.ljust(width)[col]) for col in range(width) for value in values]
        return matrix(name, 4, len(values), width, 4, struct.pack(f"<{len(chars)}H", *chars))

    header = bytearray(128)
    title = b"MATLAB 5.0 MAT-file, synthetic Unscrambler export; no customer data"
    header[: len(title)] = title
    header[124:] = b"\x00\x01IM"
    return (
        bytes(header)
        + labels("VarLabels0", LABELS)
        + labels("ObjLabels", OBJECTS)
        + matrix(
            "Synthetic", 6, len(OBJECTS), len(LABELS), 9, struct.pack(f"<{len(VALUES)}d", *VALUES)
        )
    )


if __name__ == "__main__":
    for path, data in [
        ("samples/unscrambler/synthetic.00D", native()),
        ("samples/matlab/synthetic_unscrambler.mat", mat()),
    ]:
        target = ROOT / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        print(path)
