/*
 * nirs4all-io C ABI header.
 *
 * Generated by cbindgen; do not edit by hand. Refresh with:
 *   cargo build -p nirs4all-io-capi
 *
 * The committed copy under crates/nirs4all-io-capi/include/nirs4all_io.h
 * mirrors the latest build so downstream packagers can pin the header
 * without running cargo.
 */

#ifndef NIRS4ALL_IO_H
#define NIRS4ALL_IO_H

/* Generated with cbindgen:0.27.0 */

/* This file is auto-generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Return the C ABI version string.

char *n4io_abi_version(void)
;

// Free strings returned by this ABI.
//
// # Safety
//
// `ptr` must either be null or a pointer previously returned by a
// `nirs4all-io` C ABI function that transfers string ownership to the caller.
// It must not be freed more than once.

void n4io_string_free(char *ptr)
;

// Placeholder hook used by bindings to detect that the native core is loaded.

bool n4io_core_is_available(void)
;

#endif  /* NIRS4ALL_IO_H */


