#[cfg(feature = "fmt-hdf5")]
pub mod allotrope_adf;
pub mod allotrope_asm;
pub mod animl;
pub mod asd;
pub mod avantes_ascii;
pub mod avantes_binary;
pub mod bruker_dpt;
pub mod bruker_opus;
pub mod buchi_nircal;
pub mod csv_like;
pub mod digitalsurf;
pub mod envi_sli;
pub mod erdas_lan;
pub mod excel;
// Graceful-degradation stubs for readers excluded from a feature-trimmed build.
// Compiled only when at least one heavy reader feature is OFF; with the full
// `formats-all` default every reader exists and no stub is needed.
#[cfg(not(all(feature = "fmt-hdf5", feature = "fmt-matlab", feature = "fmt-parquet")))]
pub mod excluded_stubs;
#[cfg(feature = "fmt-hdf5")]
pub mod fgi_xml;
pub mod foss_winisi;
pub mod galactic_spc;
pub mod hamamatsu_img;
#[cfg(feature = "fmt-hdf5")]
pub mod hdf5;
#[cfg(feature = "fmt-hdf5")]
pub mod hdf5_helpers;
pub mod horiba_labspec;
pub mod jasco_jws;
pub mod jcamp;
#[cfg(feature = "fmt-matlab")]
pub mod matlab;
pub mod msa;
pub mod mzml;
#[cfg(feature = "fmt-hdf5")]
pub mod netcdf;
pub mod nicolet_omnic;
pub mod numpy;
pub mod ocean_optics;
#[cfg(feature = "fmt-openspecy")]
pub mod openspecy;
#[cfg(feature = "fmt-parquet")]
pub mod parquet;
pub mod perkin_elmer;
pub mod pp_systems;
pub mod renishaw_wdf;
pub mod scio_csv;
pub mod sed;
pub mod siware_api;
pub mod spectral_matrix;
pub mod spectral_table;
pub mod sun_photometer;
pub mod svc_sig;
pub mod trivista_tvf;
pub mod usgs_aref;
pub mod viavi_micronir;
pub mod witec_wip;

mod util;

#[cfg(feature = "fmt-hdf5")]
pub use allotrope_adf::AllotropeAdfReader;
pub use allotrope_asm::AllotropeAsmReader;
pub use animl::AnimlReader;
pub use asd::AsdReader;
pub use avantes_ascii::AvantesAsciiReader;
pub use avantes_binary::AvantesBinaryReader;
pub use bruker_dpt::BrukerDptReader;
pub use bruker_opus::BrukerOpusReader;
pub use buchi_nircal::BuchiNircalReader;
pub use csv_like::CsvLikeReader;
pub use digitalsurf::DigitalSurfReader;
pub use envi_sli::EnviSliReader;
pub use erdas_lan::ErdasLanReader;
pub use excel::ExcelReader;
#[cfg(not(feature = "fmt-hdf5"))]
pub use excluded_stubs::ExcludedFgiXmlReader;
#[cfg(not(feature = "fmt-hdf5"))]
pub use excluded_stubs::ExcludedHdf5NetcdfReader;
#[cfg(not(feature = "fmt-matlab"))]
pub use excluded_stubs::ExcludedMatlabReader;
#[cfg(not(feature = "fmt-parquet"))]
pub use excluded_stubs::ExcludedParquetReader;
#[cfg(feature = "fmt-hdf5")]
pub use fgi_xml::FgiXmlReader;
pub use foss_winisi::FossWinisiReader;
pub use galactic_spc::GalacticSpcReader;
pub use hamamatsu_img::HamamatsuImgReader;
#[cfg(feature = "fmt-hdf5")]
pub use hdf5::Hdf5Reader;
pub use horiba_labspec::HoribaLabSpecReader;
pub use jasco_jws::JascoJwsReader;
pub use jcamp::JcampReader;
#[cfg(feature = "fmt-matlab")]
pub use matlab::MatlabReader;
pub use msa::MsaReader;
pub use mzml::MzmlReader;
#[cfg(feature = "fmt-hdf5")]
pub use netcdf::NetcdfReader;
pub use nicolet_omnic::NicoletOmnicReader;
pub use numpy::NumpyReader;
pub use ocean_optics::OceanOpticsReader;
#[cfg(feature = "fmt-openspecy")]
pub use openspecy::OpenSpecyReader;
#[cfg(feature = "fmt-parquet")]
pub use parquet::ParquetReader;
pub use perkin_elmer::PerkinElmerReader;
pub use pp_systems::PpSystemsReader;
pub use renishaw_wdf::RenishawWdfReader;
pub use scio_csv::ScioCsvReader;
pub use sed::SedReader;
pub use siware_api::SiwareApiReader;
pub use spectral_matrix::SpectralMatrixReader;
pub use spectral_table::SpectralTableReader;
pub use sun_photometer::SunPhotometerReader;
pub use svc_sig::SvcSigReader;
pub use trivista_tvf::TrivistaTvfReader;
pub use usgs_aref::UsgsArefReader;
pub use viavi_micronir::ViaviMicroNirReader;
pub use witec_wip::WitecWipReader;
