//! Unscrambler non-design data, Unicode binary layout 35 (`.00D`).
//!
//! Reverse-engineered against a paired MATLAB export. No vendor/reference
//! runtime is linked. Other revisions and design/model files are not decoded.
use std::collections::BTreeMap;
use std::path::Path;

use nirs4all_formats_core::{Confidence, Error, FormatProbe, Result, SourceFile, SpectralRecord};
use serde_json::json;

use super::labelled_matrix::{self, LabelledMatrix, MatrixGroup};
use super::util::read_bytes;
use crate::Reader;

const MAGIC: &[u8] = b"Non-design data File Generated by The Unscrambler ";
const REVISION: &[u8] = b"35 ";
const MIN_DATA_START: usize = 0x300;

pub struct UnscramblerReader;

impl Reader for UnscramblerReader {
    fn name(&self) -> &'static str {
        "nirs4all_formats::readers::unscrambler"
    }

    fn sniff(&self, head: &[u8], _path: &Path) -> Option<FormatProbe> {
        head.starts_with(MAGIC).then(|| {
            FormatProbe::new(
                "unscrambler-00d",
                self.name(),
                Confidence::Definite,
                "Unscrambler non-design data signature; binary revision validated on read",
            )
        })
    }

    fn read_path(&self, path: &Path) -> Result<Vec<SpectralRecord>> {
        self.read_bytes(path, &read_bytes(path)?)
    }

    fn read_bytes(&self, path: &Path, bytes: &[u8]) -> Result<Vec<SpectralRecord>> {
        let (matrix, vendor_metadata, sample_descriptors) = decode(bytes)?;
        let mut records = labelled_matrix::records(
            matrix,
            "unscrambler-00d",
            self.name(),
            SourceFile::from_bytes(path, bytes, "primary"),
        )?;
        for (record, descriptor) in records.iter_mut().zip(sample_descriptors) {
            record
                .metadata
                .insert("vendor_sample_descriptor".into(), json!(descriptor));
        }
        // Dataset-wide settings are preserved once, avoiding a large table per row.
        records[0]
            .metadata
            .insert("vendor_dataset".into(), vendor_metadata);
        Ok(records)
    }
}

fn invalid(message: &str) -> Error {
    Error::InvalidRecord(format!("Unscrambler 00D: {message}"))
}

fn u32_at(bytes: &[u8], offset: usize) -> Result<usize> {
    let raw = bytes
        .get(offset..offset.saturating_add(4))
        .ok_or_else(|| invalid("truncated integer"))?;
    Ok(u32::from_le_bytes(raw.try_into().expect("four bytes")) as usize)
}

struct Block<'a> {
    kind: usize,
    count: usize,
    stride: usize,
    data: &'a [u8],
}

fn block<'a>(bytes: &'a [u8], cursor: &mut usize, expected_id: usize) -> Result<Block<'a>> {
    let header = bytes
        .get(*cursor..cursor.saturating_add(16))
        .ok_or_else(|| invalid("truncated block header"))?;
    let kind = u32_at(header, 0)?;
    if u32_at(header, 4)? != expected_id {
        return Err(invalid("unexpected block identifier/order"));
    }
    let count = u32_at(header, 8)?;
    let stride = u32_at(header, 12)?;
    if stride == 0 {
        return Err(invalid("zero block stride"));
    }
    let size = count
        .checked_mul(stride)
        .ok_or_else(|| invalid("block size overflow"))?;
    let start = cursor
        .checked_add(16)
        .ok_or_else(|| invalid("block offset overflow"))?;
    let end = start
        .checked_add(size)
        .ok_or_else(|| invalid("block offset overflow"))?;
    let data = bytes
        .get(start..end)
        .ok_or_else(|| invalid("truncated block payload"))?;
    *cursor = end;
    Ok(Block {
        kind,
        count,
        stride,
        data,
    })
}

fn layout(block: &Block<'_>, kind: usize, stride: usize) -> Result<()> {
    if block.kind != kind || block.stride != stride {
        return Err(invalid("unsupported binary block layout"));
    }
    Ok(())
}

fn text(bytes: &[u8]) -> Result<String> {
    if !bytes.len().is_multiple_of(2) {
        return Err(invalid("misaligned UTF-16 string"));
    }
    let units: Vec<_> = bytes
        .chunks_exact(2)
        .map(|b| u16::from_le_bytes([b[0], b[1]]))
        .take_while(|&c| c != 0)
        .collect();
    String::from_utf16(&units)
        .map(|s| s.trim().to_string())
        .map_err(|_| invalid("invalid UTF-16 string"))
}

fn selection(bytes: &[u8], limit: usize) -> Result<Vec<usize>> {
    let end = bytes.iter().position(|&b| b == 0).unwrap_or(bytes.len());
    let value =
        std::str::from_utf8(&bytes[..end]).map_err(|_| invalid("invalid selection string"))?;
    let mut indices = Vec::new();
    for part in value.split(',') {
        let (start, end) = part
            .trim()
            .split_once('-')
            .unwrap_or((part.trim(), part.trim()));
        let start: usize = start
            .parse()
            .map_err(|_| invalid("invalid selection range"))?;
        let end: usize = end
            .parse()
            .map_err(|_| invalid("invalid selection range"))?;
        if start == 0 || end < start || end > limit {
            return Err(invalid("selection range out of bounds"));
        }
        // Validate bounds before expanding potentially hostile ranges.
        if indices
            .len()
            .checked_add(end - start + 1)
            .is_none_or(|n| n > limit)
        {
            return Err(invalid("selection contains too many indices"));
        }
        indices.extend(start - 1..end);
    }
    let mut sorted = indices.clone();
    sorted.sort_unstable();
    sorted.dedup();
    if sorted.len() != indices.len() {
        return Err(invalid("selection repeats an index"));
    }
    Ok(indices)
}

type Decoded = (LabelledMatrix, serde_json::Value, Vec<Vec<u32>>);

fn words(bytes: &[u8]) -> Vec<u32> {
    bytes
        .chunks_exact(4)
        .map(|b| u32::from_le_bytes(b.try_into().expect("four bytes")))
        .collect()
}

fn decode(bytes: &[u8]) -> Result<Decoded> {
    if !bytes.starts_with(MAGIC) || !bytes[MAGIC.len()..].starts_with(REVISION) {
        return Err(invalid("only non-design binary revision 35 is supported"));
    }
    if u32_at(bytes, 92)? != 35 {
        return Err(invalid("header/text revision mismatch"));
    }
    if u32_at(bytes, 248)? != 1 {
        return Err(invalid("only single-dataset files are supported"));
    }
    let mut cursor = u32_at(bytes, 252)?;
    if cursor < MIN_DATA_START || cursor > bytes.len() {
        return Err(invalid("dataset offset out of bounds"));
    }
    let header_hex: String = bytes[..cursor]
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect();
    let header = block(bytes, &mut cursor, 1000)?;
    layout(&header, 11, 276)?;
    if header.count != 1 {
        return Err(invalid("expected one dataset header"));
    }
    let name = text(&header.data[4..84])?;
    let cols = u32_at(header.data, 172)?;
    let rows = u32_at(header.data, 176)?;
    if rows == 0 || cols == 0 {
        return Err(invalid("empty matrix"));
    }
    let settings = block(bytes, &mut cursor, 1001)?;
    layout(&settings, 30, 112)?;
    if settings.count != 1 {
        return Err(invalid("expected one dataset settings block"));
    }
    let row_info = block(bytes, &mut cursor, 1002)?;
    layout(&row_info, 13, 128)?;
    let col_info = block(bytes, &mut cursor, 1003)?;
    layout(&col_info, 14, 92)?;
    if row_info.count != rows || col_info.count != cols {
        return Err(invalid("descriptor dimensions do not match matrix"));
    }
    let row_groups = block(bytes, &mut cursor, 1004)?;
    layout(&row_groups, 26, 600)?;
    let col_groups = block(bytes, &mut cursor, 1005)?;
    layout(&col_groups, 26, 600)?;
    let labels = block(bytes, &mut cursor, 1006)?;
    layout(&labels, 12, 32)?;
    let objects = block(bytes, &mut cursor, 1007)?;
    layout(&objects, 12, 32)?;
    let dataset_label = block(bytes, &mut cursor, 1008)?;
    layout(&dataset_label, 12, 32)?;
    let data = block(bytes, &mut cursor, 1009)?;
    layout(&data, 1, 4)?;
    if labels.count != cols
        || objects.count != rows
        || dataset_label.count != 1
        || rows.checked_mul(cols) != Some(data.count)
    {
        return Err(invalid("label/data dimensions do not match matrix"));
    }
    if cursor != bytes.len() {
        return Err(invalid(
            "trailing blocks/multiple datasets are not supported",
        ));
    }
    let mut metadata = BTreeMap::new();
    metadata.insert("container".into(), json!("unscrambler_00d_revision_35"));
    metadata.insert("dataset_label".into(), json!(text(dataset_label.data)?));
    let mut sample_groups = Vec::new();
    for item in row_groups.data.chunks_exact(600) {
        sample_groups.push(
            json!({"name": text(&item[..80])?, "sample_indices": selection(&item[88..344], rows)?, "vendor_flags": [u32_at(item, 80)?, u32_at(item, 84)?], "vendor_tail": words(&item[344..])}),
        );
    }
    metadata.insert("sample_groups".into(), json!(sample_groups));
    let sample_descriptors = row_info.data.chunks_exact(128).map(words).collect();
    let vendor_metadata = json!({
        "file_header_hex": header_hex,
        "dataset_header_words": words(header.data),
        "settings_words": words(settings.data),
        "column_descriptors": col_info.data.chunks_exact(92).map(words).collect::<Vec<_>>(),
    });
    let mut groups = Vec::new();
    let mut group_metadata = Vec::new();
    for item in col_groups.data.chunks_exact(600) {
        let name = text(&item[..80])?;
        let columns = selection(&item[88..344], cols)?;
        group_metadata.push(json!({"name": name, "column_indices": columns, "vendor_flags": [u32_at(item, 80)?, u32_at(item, 84)?], "vendor_tail": words(&item[344..])}));
        groups.push(MatrixGroup { name, columns });
    }
    metadata.insert("variable_groups".into(), json!(group_metadata));
    let values = data
        .data
        .chunks_exact(4)
        .map(|b| {
            let value = f32::from_le_bytes(b.try_into().expect("four bytes"));
            // Vendor missing sentinel; confirmed against NaNs in the paired export.
            if value == -9.973e23_f32 {
                f64::NAN
            } else {
                f64::from(value)
            }
        })
        .collect();
    Ok((
        LabelledMatrix {
            name,
            rows,
            values,
            groups,
            metadata,
            labels: labels
                .data
                .chunks_exact(32)
                .map(text)
                .collect::<Result<_>>()?,
            objects: objects
                .data
                .chunks_exact(32)
                .map(text)
                .collect::<Result<_>>()?,
        },
        vendor_metadata,
        sample_descriptors,
    ))
}
